version: "3.9"

services:
  node_app:
    container_name: node_app
    build:
      context: .
      dockerfile: node.dockerfile
    image: node_api
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=sashauly
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=sashauly
      - POSTGRES_PASSWORD=12345
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./utils/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  database_data:
    driver: local
